### ISSUE TITLE
Class Magefan\Community\View\Helper\SecureHtmlRenderer not found

### ISSUE THREAD

**Issue by KevinOxwork** [magefan/module-google-tag-manager#39]
Hi,

I just updated your module and got this error : 
`[main.CRITICAL: Error: Class "Magefan\Community\View\Helper\SecureHtmlRenderer" not found in /var/www/magento/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]`

Do you have an idea why ?

Regards
Kévin

**Comment by magefan** [comment]
Please make sure that you are using the latest version of https://github.com/magefan/module-community

**Comment by magefan** [comment]
@KevinOxwork , just a note that this issues can be related https://github.com/magefan/module-community/issues/31

**Comment by KevinOxwork** [comment]
Hi @magefan 
Thank you  for your help it was the origin of the problem your right. 

But i'm asking myself a question. The Helper Directory should not be in the community repository ? Just like you do with Magefan_Blog for example ?

![image](https://github.com/magefan/module-google-tag-manager/assets/29751888/d5417905-c60e-4666-ac2c-e76487f4c155)

Because the view directory is suppose to contains frontend/admin files. 

I try to put the Helper directory at the same level of Controller or Block directories and changing the files that ask SecureHtmlRenderer Class and it worked for me.

**Comment by magefan** [comment]
@KevinOxwork , could you please use this fix https://github.com/magefan/module-community/pull/32/files for the community extension? Let us know if it works well for you.

**Comment by KevinOxwork** [comment]
@magefan, i just test it and it works fine for me :) Thank you for your help and your time.
